### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by martjay** [jhj0517/Whsiper-WebUI#1] opened 2023-03-07 02:35 UTC
venv "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\\venv\Scripts\Python.exe"

Initializing Model..

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\modules\model_Inference.py", line 34, in transcribe_file
    audio = whisper.load_audio(fileobj.name)
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\Downloads\SOFTWARE\Whisper\Whsiper-WebUI-master\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Program Files\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by jhj0517** [comment] 2023-03-07 05:46
Hello, Are you sure that FFmpeg is installed on your computer? 
As mentioned in the Readme, FFmpeg can be installed from the following link:
https://ffmpeg.org/download.html

**Comment by martjay** [comment] 2023-03-07 06:03
> Hello, Are you sure that `FFmpeg` is installed on your computer? As mentioned in the Readme, `FFmpeg` can be installed from the following link: https://ffmpeg.org/download.html

ought I had it installed before. One more question, Why doesn't it support multiple video import?

**Comment by jhj0517** [comment] 2023-03-07 14:49
It would be helpful to handle multiple files at once, so I may work on adding this functionality. 
As for the timestamp in the file name, it is used to prevent file overwriting, but it may be useful to include an option to disable it?

Additionally, the error you encountered previously may have been due to the `FFmpeg\bin` folder not being added to your system PATH. 
I added information to the README about adding the `FFmpeg\bin` folder to the system PATH.

**Comment by martjay** [comment] 2023-03-08 05:16
If you want to generate multiple subtitles, it is not possible to add time stamps, because later you have to change back very troublesome, you can set the output directory to solve this problem. 

FFmpeg This error message is indeed because I did not install it, I ignored it and thought I had installed it before.

**Comment by jhj0517** [comment] 2023-03-08 06:13
Thanks for bringing this to my attention. If there is a significant demand for the option to disable adding timestamps in filenames, I will definitely consider adding it in the future. 
In the meantime, I have confirmed that there are no remaining issues with the execution of FFmpeg, so I will be closing this issue.

**Closed by jhj0517** 2023-03-08 06:13 UTC

**Comment by martjay** [comment] 2023-03-08 07:03
> Thanks for bringing this to my attention. If there is a significant demand for the option to disable adding timestamps in filenames, I will definitely consider adding it in the future. In the meantime, I have confirmed that there are no remaining issues with the execution of FFmpeg, so I will be closing this issue.

OKay
